### ISSUE TITLE
Varnish Version?

### ISSUE THREAD

**Issue by cjmurphy42** [ilons/newrelic_varnish_plugin#5]
What version of Varnish does this work with?  I set it up with Varnish 4 but I'm getting several blank charts in New Relic.

**Comment by ilons** [comment]
This is tested with Varnish version 3, I'll update the readme to include this.

**Comment by huayra** [comment]
Plans to update it to work with 4?

Anyway, will add this repo as the main source for a NewRelic plugin for Varnish in the community site.

**Comment by ilons** [comment]
@huayra: Currently I have no plan on updating to work on varnish 4, mainly due to time constraints. I do however see it as feasible that the update will be made within the next 6 months.
Please feel free to add it as main NewRelic plugin on the community site, I try to make updates and fix bugs when needed.
